config/routes.rb
Rails.application.routes.draw do
  get 'stimulus/navbar-link-votes'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "pages#dashboard"
  # Defines the root path route ("/")
  # root "posts#index"

  resources :events do
    resources :event_places, only: [:index, :create]
  end

  resources :event_places, only: [:index, :show] do
    member do
      get "vote", to: "event_places#vote"
    end
  end

  resources :groups, only: [:index, :new, :create]

  get 'notifications', to: 'notifications#index'
end

app/views/shared/_filtered_places.html.erb
<div class="places-container <%= "all-selection" unless event.places.count < 3 %>" data-places-target="list">

  <% places.each do |place| %>
    <% if event.places.count < 3 %>
      <% if event.places.exclude?(place) %>
        <%= link_to event_event_places_path(event_id: event.id, place_id: place.id), data: { turbo_method: :post, action: "click->places#selectCard", id: place.id } do %>
          <!-- Add an extra level of indentation for the nested div -->
          <%= render "events/place_card", place: place, event: event %>
        <% end %>
      <% else %>
        <%= render "events/place_card", place: place, event: event %>
      <% end %>
    <% else %>
      <%= render "events/place_card", place: place, event: event %>
    <% end %>
  <% end %>

  <% if event.places.count >= 1 %>
    <div class="list-cta d-flex">
       <h4 style="margin: 12px; padding: 7px;"><%= event.places.count %> place(s) selected</h4>
       <% if event.places.count == 3 %>
          <%= link_to "Vote", event_event_places_path(event), class:"btn custom-btn", style:"margin: 12px;" %>
       <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
     <div class="footer">
        <div class="footer-content">
            <div class="footer-section about">
                <h2 class="h2-footer">About</h2>
                <p class="footer-contact-hover">Informations</p>
                <p class="footer-contact-hover">Blog </p>
                <p class="footer-contact-hover">Newsletter</p>
            </div>
            <div class="footer-section links">
                <h2 class="h2-footer">Links</h2>
                <ul>
                    <li><p class="footer-contact-hover">Accueil</p></li>
                    <li><p class="footer-contact-hover">Découvrir</p></li>
                    <li><p class="footer-contact-hover">Réserver</p></li>
                </ul>
            </div>
            <div class="footer-section contact">
                <h2 class="h2-footer">Nous contacter</h2>
                <p class="footer-contact-hover"><i class="fas fa-envelope"></i> contact@blablabla.com</p>
                <p class="footer-contact-hover"><i class="fas fa-phone"></i> +33 (0)1 23 45 67 89</p>
                <div>
                  <i class="fab fa-instagram social-media-links fa-lg"></i>
                  <i class="fab fa-facebook social-media-links fa-lg"></i>
                  <i class="fa-brands fa-x-twitter social-media-links fa-sm"></i>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            &copy; Made with love by Abdes, Laure, Arthur & Lucile
            <i class="fa-duotone fa-heart"></i>
        </div>
    </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "" do %>
      <%= image_tag "https://res.cloudinary.com/djwmjh3zt/image/upload/v1701706979/Ideal_Place_dam53o.png", class:"logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto">

        <% if user_signed_in? %>
        <!-- ajout cloche dropdown -->
          <li class="nav-item d-flex dropdown">
            <a class="nav-link" id="navbarDropdown" data-bs-toggle="dropdown" alt="dropdown menu"> <i class='fa-solid fa-bell fa-lg' style='color: #FCA601;'></i></a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% current_user.notif %>
              <%# <%= link_to "Vote for event #{ @event.name }", event_event_places_path(@event), class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar", title: current_user.nickname, alt: "dropdown menu", id: "navbarDropdown", data: {bs_toggle: "dropdown"} %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>