config/routes.rb
Rails.application.routes.draw do
  get 'stimulus/navbar-link-votes'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "pages#dashboard"
  # Defines the root path route ("/")
  # root "posts#index"

  resources :events do
    resources :event_places, only: [:index, :create]
  end

  resources :event_places, only: [:index, :show] do
    member do
      get "vote", to: "event_places#vote"
    end
  end

  resources :groups, only: [:index, :new, :create]

  get 'notifications', to: 'notifications#index'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :group

  #has_many :users, through: :group_users
  has_many :event_users, dependent: :destroy
  has_many :event_places, dependent: :destroy
  has_many :places, through: :event_places

  after_initialize :set_default_status, if: :new_record?


  STATUS = %w(Created Voted Passed)

  validates :selected_group_name, :date, :start_time, presence: true

  def voted_by_user(user)
    !Favorite.where(favoritable_id: event_places.pluck(:id), favoritor_id: user.id).empty?
  end

  def total_vote
    self.event_places.map { |event_place| event_place.favoritors.count }.sum
  end

  private

  def set_default_status
    self.status ||= 'Created'
  end
 #  validates :status, inclusion: { in: STATUS, message: "%{value} is not a valid status type" }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @selected_group_name = @event.selected_group_name || "No group"
    @event_name = @event.name
    @event_places = @event.event_places

    @group_users = @event.group.users

    # Check for category filtering
    @places = params[:category].present? ? Place.where(category: params[:category]) : Place.all


    @markers = @places.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        info_window_html: render_to_string(partial: "info_window1", locals: { place: place }),
        marker_html: render_to_string(partial: "marker1", locals: { place: place })
      }
    end

    @markers_group_users = @group_users.geocoded.map do |group_user|
      {
        lat: group_user.latitude, # default latitude
        lng: group_user.longitude, # default longitude
        info_window_html: render_to_string(partial: "info_window2", locals: { group_user: group_user }),
        marker_html: render_to_string(partial: "marker2", locals: { group_user: group_user })
      }
    end

    # On a un array de hash avec plein de clés dont lat: lng:
    # on va mapper sur l'array, on va être sur chaque hash
    # on va return à chaque fois un array avec la clé correspondante

    @barycenter = @markers_group_users
    @barycenter = @barycenter.map do |marker|
      [marker[:lat], marker[:lng]]
    end

    @barycenter = Geocoder::Calculations.geographic_center(@barycenter)

    @barycenter_marker = {
      lat: @barycenter[0],
      lng: @barycenter[1],
      info_window_html: "<div class='barycenter'>Barycenter</div>",
      marker_html: render_to_string(partial: "marker3", locals: { barycenter: @barycenter })
    }

    @places = @places.select { |place| place.distance_from(@barycenter) < 2 }
    places_ids = @places.pluck(:id)
    @places = Place.where(id: places_ids).order(:id)

    @markers = @places.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        info_window_html: render_to_string(partial: "info_window1", locals: { place: place }),
        marker_html: render_to_string(partial: "marker1", locals: { place: place })
      }
    end

    # @places = Place.where(Place.distance_from(@barycenter_marker))

    @markers = @markers.concat(@markers_group_users).push(@barycenter_marker)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @event = Event.new
    @event.name = params[:name] # Set the name attribute from the form parameters
    @groups = Group.all
  end

  def create
    @event = Event.new(event_params)
    @event.start_time = params['event']['date'].to_time.strftime('%H:%M')
    @event.user = current_user
    selected_group_name = params[:event][:selected_group_name]
    group = Group.find_by(name: selected_group_name)
    if group
      @event.group = group
      @event.group_id = group.id # Assign the group_id explicitly
    else
      # Handle the scenario where the group does not exist
      # You can add code here to create a new group or handle the error as required
    end

    if @event.save
      redirect_to event_path(@event)
    else
      @groups = Group.all
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :start_time, :selected_group_name)
  end
end

app/views/events/_form.html.erb
<%= simple_form_for :event do |f| %>
  <%= f.input :name %>
  <%= f.input :date %>
  <%= f.input :start_time %>
  <%= f.submit class: "btn btn-primary mt-4" %>
  <%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
  %>
  <% end %>

app/views/events/_index.html.erb
<div class="container">
  <div class="row">
    <% sorted_events = events.order(date: :asc) %>
    <% sorted_events.each do |event| %>
      <%= link_to event_event_places_path(event), class: "col-md-4 p-2 mb-3" do %>
        <div class="card" style="height: 100%;">
          <div class="card-body d-flex flex-column justify-content-between" style="height: 340px">
            <h5 class="card-title mb-2"><strong style="color: #FCA601"><%= event.name %></strong> with <%= event.group.name %></h5>
            <div class="mb-2">
              <% # Sort the group users by putting the event user first %>
              <% sorted_group_users = event.group.group_users.sort_by { |group_user| group_user.user == event.user ? 0 : 1 } %>
              <% sorted_group_users.each do |group_user| %>
                <% if group_user.user.photo.attached? %>
                  <% if group_user.user == event.user %>
                    <%= cl_image_tag group_user.user.photo.key, class: "avatar", style: "width: 80px; border-color: #FCA601" %>
                  <% else %>
                    <%= cl_image_tag group_user.user.photo.key, class: "avatar", style: "width: 60px;" %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
            <p class="card-text"><i class="far fa-calendar"></i> <%= event.date.strftime("%d/%m/%Y") %></p>
            <p class="card-text"><i class="far fa-clock"></i> Start Time: <%= event.start_time.strftime("%H:%M %p") %></p>

            <div class="mt-auto">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <p class="card-text">Vote: <%= event.total_vote %> / <%= event.group.users.count %></p>
                </div>
                <div>
                  <% if event.status == "Voted" || event.status == "Passed" %>
                    <div>
                      <% event.event_places.each do |event_place| %>
                        <% if event_place.selected == true %>
                          <strong><i class="fa-regular fa-circle-check me-2" style="color: #0C7E65"></i>Selected:</strong>
                          <%= event_place.place.name %>
                        <% end %>
                      <% end %>
                    </div>
                  <% elsif event.voted_by_user(current_user) == false %>
                    <div>
                      <div class="btn custom-btn">Go vote!</div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/_info_window.html.erb
<h2><%= place.name %></h2>
<p><%= place.address %></p>
<p><%= place.phone %></p>
<p><%= place.second_category %></p>
<p><%= place.third_category %></p>

app/views/events/_info_window1.html.erb
<h2><%= place.name %></h2>
<p><%= place.address %></p>
<p><%= place.phone %></p>

app/views/events/_info_window2.html.erb
<h2><%= group_user.first_name %></h2>
<p><%= group_user.address %></p>

app/views/events/_marker1.html.erb
<%= image_tag "greenlogo2.png", class: "map-place-marker", height: 51, width: 37, alt: "event_places", data: {places_target: "marker", id: place.id} %>

app/views/events/_marker2.html.erb
<div>
  <%= cl_image_tag group_user.photo.key, alt: "Logo", class: "rounded-circle avatar-bordered", title: group_user.nickname %>
</div>

app/views/events/_marker3.html.erb
<%= image_tag "logo-laura.png", height: 35, width: 35, alt: "Barycenter" %>

app/views/events/_place_card.html.erb
<div class="card card-index mb-4 <%= event.places.include?(place) ? "card-index-selected" : "" %>" data-id="<%= place.id %>" data-places-target="card">
  <div class="row">
    <!-- image place -->
    <div class="col-sm-2">
      <% if place.photo.attached? %>
        <%= cl_image_tag place.photo.key, class: "place-picture", style:"height: 100%;" %>
      <% end %>
    </div>
    <!-- descriptif texte -->
    <div class="col-sm-10">
      <div class="card-body" style="height: 200px">
        <h5 class="card-title"><%= place.name %> - <%= place.category %></h5>
        <br>
        <p class="card-text"><i class="fas fa-map-marker-alt"></i>  <%= place.address %></p>
        <p class="list-group-item"><i class="far fa-clock"></i>  Opening Hours: <%= place.opening_hours.strftime("%H:%M %p") %> </p>
        <p class="list-group-item"><i class="fas fa-star"></i>   <%= place.rating %>/5</p>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <h1>Ideal Place </h1>
  <h2 style> Where your event begins !</h2>
    <%# <div class="navbar" id="myNavbar"> %>
        <%# <a href="#home">Home</a> %>
        <%# <a href="#profile">Profile</a> %>
        <%# <a href="#dashboard">Dashboard</a> %>
        <%# <a href="#contact">Contact</a> %>
        <%# <a href="javascript:void(0);" class="icon" onclick="typeOfMenu()"> %>
            <%# &#9776; %>
        <%# </a> %>
    <%# </div> %>

<!-- Créer cela en stimulus dès que temps dispo -->
  <%# <script>
    function typeOfMenu() {
      let x = document.getElementById("myNavbar");
        if (x.className === "navbar") {
          x.className += " responsive";
        } else {
          x.className = "navbar";
        }
      }
  </script> %>

  <div class="row">
    <div class="col-sm-12">
      <%= link_to 'Create event', new_event_path, class:"btn btn-success" %>
      <% @events.each do |event| %>
          <div class= "col-sm-12">
            <div class="h-100">
             <p class="mt-2"> <%= event.name %> </p>
              <%= link_to 'See event', event_path(event), class:"btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

</div>

app/views/events/new.html.erb
<div class="container">
 <h2 class="h2-new">Where your event begins!</h2>
 <div class="row">
  <div class="col-md-8">
     <!-- partie gauche -->
     <h4 class="my-9 mb-3 h4-new">Your event name is "<%= params[:name] %>"</h4>
    <%= simple_form_for @event, url: events_path do |f| %>
     <%= f.input :name, as: :hidden, input_html: { id: 'event_name', value: params[:name] } %>
    <%= f.input :selected_group_name, as: :hidden, input_html: { id: 'selected_group_name' } %>
     <div class="groups">
      <div class="row">
       <% current_user.groups.each do |group| %>
        <div class="col-md-4 mb-3">
         <div class="card" onclick="selectCard(this)">
          <!-- Your existing card content -->
          <div class="card-body" style="height: 447px;">
           <!-- Add some margin and padding to the card title -->
           <h5 class="card-title" style="margin-bottom: 10px; padding-bottom: 10px; border-bottom: 1px solid #E0E0E0;"><%= group.name %></h5>
           <div>
            <strong><i class="fas fa-user"></i> Members</strong>
            <!-- Add some margin and padding to the member avatars -->
            <div style="margin-top: 10px; padding: 5px;">
             <% group.group_users.each do |group_user| %>
              <% if group_user.user.photo.attached? %>
               <%= cl_image_tag group_user.user.photo.key, class: "avatar avatar-gap", style:"width: 60px;" %>
               <!-- Uncomment the following line to show the member names -->
               <%# <span> <%= group_user.user.first_name %>
              <% end %>
             <% end %>
            </div>
           </div>
          </div>
         </div>
        </div>
       <% end %>
      </div>
     </div>
  </div>
     <!-- partie droite -->
  <div class="col-md-4">
   <div data-controller="datepicker">
   <%= f.input :date, as: :string, input_html: { id: "event_date", placeholder: "DD-MM-YYYY", style: "visibility: hidden", class: "datepicker" }, label: false %>
  </div>
  <%= f.submit "Create Event", class: "btn custom-btn custom-btn-small-new mb-4" %>
  <% end %>
  </div>
      <br>
 <!-- Add this closing tag for the form -->
   </div>
  </div>
 </div>
</div>
<script>
 function selectCard(element) {
  var cards = document.querySelectorAll('.card');
  cards.forEach(function(card) {
   card.classList.remove('card-index-selected');
  });
  element.classList.add('card-index-selected');
  var groupName = element.querySelector('.card-title').innerText;
  document.getElementById('selected_group_name').value = groupName;
 }
</script>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
     <!-- <div class="flash flash-success alert alert-dismissible fade show" role="alert">
        <span><strong>Yay!</strong> 🎉 You have successfully created your event! Let's continue.</span>
          <a data-bs-dismiss="alert" aria-label="Close">
            <i class="fas fa-times"></i>
          </a>
      </div>
      -->
      <br>
    </div>
  </div>
<div class="d-flex justify-content-between mb-5">
  <div class="card-category col-md-6 p-3" style="color: white; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2); background-color: #1D475E; border-radius: 4px" >
    <div class="d-flex justify-content-between">

      <div class="col-md-5">

        <h2><%= @event_name %> </h2>

        <br>

        <h5><i class="far fa-calendar"></i>  <%= @event.date.strftime("%d/%m/%Y") %> - <%= @event.start_time.strftime("%H:%M %p") %></h5>
      </div>

      <div style="margin-left: 20px;" class="col-md-7">

        <% @event.group.group_users.each do |group_user| %>
          <%= cl_image_tag group_user.user.photo.key, class: "avatar avatar-gap", title: group_user.user.nickname, style: "width: 60px;" %>
        <% end %>
      </div>
    </div>
  </div>
  <h3 style="margin: 30px; padding-right: 150px;"> We found <%= @places.count %> result(s)</h3>
</div>

  <!-- events/show.html.erb  w-50 mb-2 justify-content-between-->
      <div class="d-flex bd-highlight w-50 mb-2" data-controller="filter">
        <%= link_to "All", event_path(@event), class: "p-2 flex-fill bd-highlight me-2 btn custom-margin #{active_filter_class(nil)}", data: { action: "filter#filter" } %>
        <%= link_to "Catering", event_path(@event, category: 'Catering'), class: "p-2 flex-fill bd-highlight me-2 btn custom-margin #{active_filter_class('Catering')}", data: { action: "filter#filter" } %>
        <%= link_to "Entertainment", event_path(@event, category: 'Entertainment'), class: "p-2 flex-fill bd-highlight me-2 btn custom-margin #{active_filter_class('Entertainment')}", data: { action: "filter#filter" } %>
        <%= link_to "Culture", event_path(@event, category: 'Culture'), class: "p-2 flex-fill bd-highlight btn custom-margin #{active_filter_class('Culture')}", data: { action: "filter#filter" } %>
      </div>

  <div class="event-container" data-controller="places">

    <%= render 'shared/filtered_places', places: @places, event: @event %>

    <div class="map-display"
        data-target="filter.map"
        data-places-target="map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>