config/routes.rb
Rails.application.routes.draw do
  get 'stimulus/navbar-link-votes'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "pages#dashboard"
  # Defines the root path route ("/")
  # root "posts#index"

  resources :events do
    resources :event_places, only: [:index, :create]
  end

  resources :event_places, only: [:index, :show] do
    member do
      get "vote", to: "event_places#vote"
    end
  end

  resources :groups, only: [:index, :new, :create]

  get 'notifications', to: 'notifications#index'
end

app/views/pages/dashboard.html.erb
<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link active text-white" data-bs-toggle="tab" href="#myeventsSection">MY EVENTS</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" data-bs-toggle="tab" href="#othereventsSection">PASSED EVENTS</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" data-bs-toggle="tab" href="#mygroupsSection">MY GROUPS</a>
  </li>
</ul>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-12">
      <div class="tab-content">

        <div class="tab-pane fade" id="mygroupsSection">
          <div class="groups">
            <div class="row">
              <% current_user.groups.each do |group| %>
                <% if group.user == current_user %>
                  <div class="col-md-4 mb-3">
                    <div class="card">
                      <div class="card-body">
                        <!-- Add some margin and padding to the card title -->
                        <h5 class="card-title" style="margin-bottom: 10px; padding-bottom: 10px; border-bottom: 1px solid #e0e0e0;"><%= group.name %></h5>
                        <div>
                          <strong><i class="fas fa-user"></i>  Members</strong>
                          <!-- Add some margin and padding to the member avatars -->
                          <div style="margin-top: 10px; padding: 5px;">
                            <% group.group_users.each do |group_user| %>
                              <% if group_user.user.photo.attached? %>
                                <%= cl_image_tag group_user.user.photo.key, class: "avatar avatar-gap", style:"width: 60px;", title: group_user.user.nickname %>
                                <!-- Uncomment the following line to show the member names -->
                                <%# <span> <%= group_user.user.first_name %>
                              <% end %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
          <%= link_to "Add Group", new_group_path, class: "btn custom-btn mb-2"%>
        </div>

        <div class="tab-pane fade show active" id="myeventsSection">
          <%= render 'events/index', events: @events %>
        </div>

        <div class="tab-pane fade" id="othereventsSection">
          <%= render 'events/index', events: @passed_events %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-home">
    <div id="text-overlay">
        <div class="row">
          <div class="col-12">
            <div class="home-title">
              <%= image_tag "ideal-place.png", alt:"Ideal Place - Where your events begin -logo texte", class:"space-between-logo-accroche", style:"height: 75px;" %><br>
              <%= image_tag "dawn.png", alt:"designed sun", class:"sun", style:"height: 140px;" %>
            </div>
            <%= image_tag "where-your-events-begin.png", alt:"Ideal Place - Where your events begin - accroche", class:"space-between-accroche-input", style:"height: 50px;" %><br>
            <%= form_with url: new_event_path, method: :get, html: {class: "mb-4", data: {search_movies_target: "form"}} do |f| %>
              <%= f.text_field :name,
                              class: "underline-input",
                              value: params[:name],
                              placeholder: "Your event name!"
              %>

            <%= f.submit "➜", class:"form-arrow", data: { turbo: false } %>
            <% end %>
            <!-- placage des 5 images à intégrer pour la déco à mettre en position absolute ! -->
            <%= image_tag "green-vertical-lines.png", alt:"Green vertical lines", class:"green-vertical-lines" %>
            <%= image_tag "green-horizontal-lines.png", alt:"Green horizontal lines", class:"green-horizontal-lines" %>
            <%= image_tag "demi-sphere-orange-verte.png", alt:"Demi-sphere-orange-verte", class:"demi-sphere-orange-verte" %>
            <%= image_tag "demi-sphere-orange-jaune.png", alt:"Demi-sphere-orange-jaune", class:"demi-sphere-orange-jaune" %>
          </div>
        </div>
        </div>
      </div>

</div>