config/routes.rb
Rails.application.routes.draw do
  get 'stimulus/navbar-link-votes'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "pages#dashboard"
  # Defines the root path route ("/")
  # root "posts#index"

  resources :events do
    resources :event_places, only: [:index, :create]
  end

  resources :event_places, only: [:index, :show] do
    member do
      get "vote", to: "event_places#vote"
    end
  end

  resources :groups, only: [:index, :new, :create]

  get 'notifications', to: 'notifications#index'
end

app/models/event_place.rb
class EventPlace < ApplicationRecord
  belongs_to :place
  belongs_to :event
  acts_as_favoritable

  # validates :duration, :distance, :transport_mode, presence: true
end

app/controllers/event_places_controller.rb
class EventPlacesController < ApplicationController
  before_action :set_event, only: [:new, :create, :index]
  before_action :set_event_place, only: [:show, :vote]

  def new
    @event_place = @event.event_places.new
  end

  def create
    places_ids = params[:ids_array].map(&:to_i)
    category = params[:category]
    @place = Place.find(params[:place_id])
    @event_place = EventPlace.new(event: @event, place: @place)
    selected_places = Place.where(id: places_ids).order(:id)
    unless category == "none"
      selected_places = selected_places.where(category: category)
    end
    if @event_place.save
      respond_to do |format|
        format.html { redirect_to event_path(@event) }
        format.text { render partial: "shared/filtered_places", formats: :html, locals: { event: @event, places: selected_places } }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @event_places = @event.event_places
    @places = @event_places.map { |event_place| event_place.place }

    # TODO get places with active record query, and ad geocoded below

    @geomarkers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        info_window_html: render_to_string(partial: "event_places/info_window4", locals: { place: place }, formats: :html),
        marker_html: render_to_string(partial: "event_places/marker4", locals: { place: place }, formats: :html)
      }
    end
    voted_by_all_users
  end

  def show
  end

  def vote
    current_user.favorite(@event_place) unless @event_place.event.voted_by_user(current_user)
    redirect_to event_event_places_path(@event_place.event)
  end

  def voted_by_all_users
    if @event.total_vote == @event.group.users.count
      favorite_event_place = @event.event_places.max_by { |event_place| event_place.favoritors.count }
      favorite_event_place.selected = true
      favorite_event_place.save
      @event.status = "Voted"
      @event.save
    end

    # @vote_count = 0
    # @vote_count_event_place = 0

    # @event.event_places.each do |event_place|
    #   @place_vote_count = event_place.favoritors.count
    #   if @place_vote_count == @event.group.users.count
    #     event_place.selected = true
    #     @event.status = "Voted"
    #     event_place.save
    #     @event.save
    #   end
    # end
  end

  def destroy
    @event_places.delete(event_place)
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_event_place
    @event_place = EventPlace.find(params[:id])
  end

  def event_place_params
    params.require(:event_place).permit(:event_id, :place_id)
  end
end

app/views/event_places/_info_window4.html.erb
<h2><%= place.name %></h2>
<p><%= place.address %></p>

app/views/event_places/_marker4.html.erb
<%= image_tag "marker_4.png", height: 62, width: 42, alt: "event_places" %>

app/views/event_places/index.html.erb
<div class="container" style="display: flex; flex-direction: column;">
  <div class="row">
  <% @event_places.each do |event_place| %>
    <div class="col-md-4">
      <div class="card mb-4 <%= event_place.selected ? "card-index-selected" : "unselected" %>">
        <div class="row">
          <!-- Image of the place -->
          <div class="col-sm-4">
            <% if event_place.place.photo.attached? %>
              <%= cl_image_tag event_place.place.photo.key, class: "place-picture", style: "height: 100%;" %>
            <% end %>
          </div>
          <!-- Card body -->
          <div class="col-sm-8">
            <div class="card-body" style="height: 200px; overflow: hidden;">
              <div class="d-flex justify-content-between">
                <h5 class="card-title"><%= event_place.place.name %></h5>
                <%= link_to "X", event_place_path(event_place), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, style: "opacity: 1;" %>
              </div>
              <div class="content-with-margin">
                <p class="card-text"><i class="fas fa-map-marker-alt"></i> <%= event_place.place.address %></p>

                <div class="d-flex justify-content-between align-items-center" style="position: absolute; bottom: 1px">
                  <% if event_place.favoritors %>
                    <div>
                      Votes: <%= event_place.favoritors.count %> / <%= @event.group.group_users.count %>
                      <% @event.group.group_users.each do |group_user| %>
                        <% if event_place.favoritors.include?(group_user.user) %>
                          <%= cl_image_tag group_user.user.photo.key, class: "avatar", title: group_user.user.nickname %>
                        <% end %>
                      <% end %>
                    </div>
                  <% end %>
                  <div class="form-check" style="color: #0C7E65;">
                    <% if @event.voted_by_user(current_user) %>
                      <%= current_user.favorited?(event_place) ? "✓ Voted" : "" %>
                    <% else %>
                      <%= link_to "Vote", vote_event_place_path(event_place), class: "btn custom-btn", style: "margin-left: 55px; margin-top: 20px" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


  <div class="row" class="mapboxgl-popup-content mapboxgl-popup-close-button">
    <div style="width: 98%; height: 600px; margin: auto; align-self: center;"
      data-controller="map"
      data-map-markers-value="<%= @geomarkers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

</div>

app/views/event_places/show.html.erb
<h1>Show </h1>
<% if @event_place.favoritors %>
  <h2>New : Owner <%= current_user.first_name%></h2>
  <ul>
    <% @event_place.favoritors.each do |favorite| %>
      <li><%= favorite.first_name %></li>
    <%end%>
  </ul>
<%end%>

app/views/event_places/vote.html.erb
<div class="col-md-6">
      <div style="width: 100%; height: 600px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>